### ISSUE TITLE
Correct sizing of animated gif thumbnail on Home and Detail pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1060]
The thumbnail-upload module supports upload of .gif. What's more, the Explore page successfully shows the animated gif playing at a properly scaled size on the layer or story card.

However, on the Home and Layer/Story detail pages, the .gif is not sized to the proper proportion. For example, see the homepage below when a story with an animated gif thumbnail is featured.

_Completion of this ticket means that the homepage and detail pages automatically scale the size of the gif upload, as is done successfully on Explore right now, or at least guidance is given to the user on what the size of the gif must be on upload for it to be sized appropriately_

![screen shot 2017-10-20 at 10 21 20 am](https://user-images.githubusercontent.com/2573761/31841130-c779a5ea-b5ad-11e7-9775-77acf4ea7e41.jpg)

**Comment by emilyashley** [comment]
This is an easy fix if we throw in some css for it. However, resizing on the front end isn't that performant so if we're doing that for all thumbnail gifs even on the search and detail pages we may wanna address sending/storing the right size or only allowing up to a certain size to be uploaded.

Is it acceptance criteria for all of that to be addressed right now? Or is this ticket purely for the visual? We can always follow up with performance later.

**Comment by Coop56** [comment]
This is ready for review now.  I took it further than the original visual ticket.  I also rewrote the backend thumbnail saving to allow the actual gifs to be resized properly so that we aren't just resizing it on the frontend.  I was also able to refactor the resizing of the static thumbnails a bit to remove an extra dependency that we don't need anymore.  @emilyashley feel free to review the PR now.
