### ISSUE TITLE
In edit mode, feature pop-ups are misplaced

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1070]
**issue**

As a user, when I enter edit-mode for a layer and click on a feature I want to edit, the pop-up on the feature is often times appearing in the bottom-left of my screen...partially hidden behind the timeline and sidebar. This is preventing me from seeing the pop up and clicking on the buttons in the pop up (i.e. edit attributes, edit feature, etc). 

See video of user evidence:

https://www.dropbox.com/s/ycq6fte6yldtt7l/editing_bug.mov?dl=0

**Comment by emilyashley** [comment]
Hey this is still an issue; the commit here seems to try and fix it https://github.com/MapStory/MapLoom/commit/fd2dfa9463d990cb859e243013be5b97f2a5f600 but there are `.feature-info-box-popup` rules higher in the cascade that are shared with StoryPins in app.less so these changes are never rendered --- which I guess is a good thing otherwise this might have misplaced storypins. Ideally they wouldn't be sharing the same rules tho.

Gonna pick this one back up w/ #1139 and get the ol-overlay-container to correctly compute placement upon feature selection.

**Comment by emilyashley** [comment]
- [x] ensure maploom less assets build in a set order; unsure why this cascade was different for coop than it was for me

**Comment by emilyashley** [comment]
Refactored duplicate less / rectified cascade with https://github.com/MapStory/MapLoom/pull/44

**Comment by emilyashley** [comment]
Attached click position for feature info pop-up positioning rather than getNewPositionFromGeometry

remove prior cleverness of getNewPositionFromGeometry here
it's not alway returning reliable geometries for overlay
clickPosition is better for now

Don’t expose or save this clickPosition as the position of this feature

commit here: https://github.com/MapStory/MapLoom/commit/578db4a392cf6313601e7f6d8cd537454ba1c806

Will need to trigger django-maploom build to see these changes. 

NOTE: this falls short on keeping the pop-up centered over the geometry while user zooms in or out. Will make follow up issue, but it's not a user blocker.

**Comment by emilyashley** [comment]
note to self: This ticket was specifically addressing feature info popups from the Layer Editor.
 check in that #947 is still solved for feature popups on layer detail page.
