### ISSUE TITLE
Make new layers draft until user who uploaded it marks it "published"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1134]
When a user uploads a new layer, the layer is marked "published" in the metadata modal by default This promotes  a lot of low-quality layers from being published before they are ready.

**Request**

1. We should not have layers set to 'published' by default. They should be draft - only viewable by the person that uploaded them in the first place, accessible from his/her profile as DRAFT.

2. Once the user selects to Publish the layer, then the layer becomes viewable in Explore by all visitors to Explore.

3. In making this change, it would be good to make the Publish option more prominent in the UI. Right now it sits halfway down in the metadata modal and is a simple check box. Perhaps a toggle on/off treatment of some kind that either sits at the very top of the metadatmodal, or is pulled out onto the detail page itself near the "delete storylayer" button that is available to owners of the layer on the detail page. Defer to the project designer.
![screen shot 2017-12-01 at 4 06 22 pm](https://user-images.githubusercontent.com/2573761/33517517-69d248b0-d74b-11e7-9b1d-15fb1b8fa306.jpg)

**Comment by emilyashley** [comment]
context note: this is a change introduced by #660 

the modal is a django bootstrapped form, so to change the UI might have to step away from implementing it that way (or as a modal at all)
 
This is a good candidate for making a sub-task list.

**Comment by emilyashley** [comment]
Notes to self:

here's where it's set in geonode 
https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L742

here's where we customize it for map/mapstories https://github.com/MapStory/mapstory/blob/master/mapstory/mapstories/models.py#L196 - 206 but extending the Layer model in this same way doesn't work because layers from importer seem to already have an ID so the conditional is never triggered

and `settings.RESOURCE_PUBLISHING` is not the same thing as setting this default it's something else
