### ISSUE TITLE
Cannot select features in edit mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1139]
A user entering edit mode on a layer expects to be able to edit feature geometries and attributes by clicking on the feature on the map. However, in many cases it doesn't seem like the user is able to select the feature.

See this video for illustration: https://www.dropbox.com/s/2f7b8fntleso0i7/editing_no_feature_select.mov?dl=0.

It uses https://mapstory.org/layers/invasive_birds_d9040c79 as an example.

**Comment by emilyashley** [comment]
Running into this as a blocker for fully verifying the zoom on #1071 - updated the name of that issue to reflect I'm only testing _added_ features to the map, not "edited" features. 

Curious if this inability to click to edit is for all types of feature (LINES, POLY?) or just POINT features.

**Comment by emilyashley** [comment]
also referencing issues https://github.com/MapStory/mapstory/issues/1070 and https://github.com/MapStory/mapstory/issues/947 if those are related -- they might share the same classes / code? both appear to be merged/closed

1070 was addressed with this I take? https://github.com/MapStory/MapLoom/commit/fd2dfa9463d990cb859e243013be5b97f2a5f600#diff-51a5db0810296617518e816a8b32b981

**Comment by josellausas** [comment]
These are my findings so far:

While investigating this issues I came across multiple error messages that need to be investigated (even if they are not the the cause for this issue) since these might be causing unexpected behavior and side effects.

The layers I used for testing are:
- lewisandclark.csv
- american-civil-war.zip

+ Geoserver errors when loading layer
    - Geoserver errors when loading layer.
![could not add layer because it does not have a name](https://user-images.githubusercontent.com/4162671/34683130-b7792542-f466-11e7-8739-c8ec0b663153.png)

    - Geoserver failed to load store.
![failed to import](https://user-images.githubusercontent.com/4162671/34683200-e9da7f9a-f466-11e7-8e01-c65af5a70134.png)

    - Geoserver no such style
![geo server no such style 2](https://user-images.githubusercontent.com/4162671/34683282-2e536a88-f467-11e7-950c-97c0275b4c4b.png)

    - Geoserver no such feature type
![geoserver no such feature type](https://user-images.githubusercontent.com/4162671/34683311-48d430d6-f467-11e7-8540-50abd57f42c4.png)

- Geogig 500 merge error.
![screen shot 2018-01-03 at 1 33 31 pm](https://user-images.githubusercontent.com/4162671/34683326-5b8d45aa-f467-11e7-8425-7a1fdefed5cd.png)
![failed to load resource](https://user-images.githubusercontent.com/4162671/34683332-63f41340-f467-11e7-83f6-18180fb137a2.png)

- Geofence fails to find matching users
![geofence](https://user-images.githubusercontent.com/4162671/34683347-69b64bea-f467-11e7-8b14-8a2b592b97b4.png)

- WMS no such operation

![invalid projection](https://user-images.githubusercontent.com/4162671/34683413-97906ae6-f467-11e7-893e-9a699bdc96e5.png)

- Projection outside its valid area

![screen shot 2018-01-03 at 3 27 04 pm](https://user-images.githubusercontent.com/4162671/34683435-a45f5566-f467-11e7-85d4-70dc200399cd.png)

Creating issues for these...
