### ISSUE TITLE
Question: Do we need to be loading all the basemaps into editor?

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1141]
Currently it appears we are loading a large number of basemaps into the editor. In the future, when we let an editor toggle between basemaps (i.e. lenses) that makes sense. But right now, when we don't let the user toggle the basemap in editing should we be loading all these basemaps? It appears from a user standpoint that it slows down the process of loading the layer features when entering edit mode.

![screen shot 2017-12-19 at 11 04 44 am](https://user-images.githubusercontent.com/2573761/34169454-1442e5f2-e4ad-11e7-8246-3ae0741cf8af.jpg)

**Comment by emilyashley** [comment]
Closed with https://github.com/MapStory/MapLoom/commit/85291c0aa7c8eca6439a788f917c55d25e38d2f6

Green light for allowing basemap selection in Layer History view since we're loading them all in on the rootscope w/ maploom anyway? It also has less side effects than changing the ServerService right now. 

You can now select a basemap on the main editor sidebar, and the selection persists on the map when you're viewing the history sidebar as well. Selection expires when user leaves the editor session. Default is same as general maploom: World Light.

This work for y'all? @jonpmarino @lhcramer 

![screen shot 2017-12-29 at 8 01 36 pm](https://user-images.githubusercontent.com/15912063/34450606-1f10bfc6-ecd3-11e7-9e23-ec0f3c21f7d5.png)
![screen shot 2017-12-29 at 7 32 07 pm](https://user-images.githubusercontent.com/15912063/34450581-a0ac9bfa-ecd2-11e7-8825-6d432eedd079.png)
![screen shot 2017-12-29 at 7 58 44 pm](https://user-images.githubusercontent.com/15912063/34450591-b9d83c56-ecd2-11e7-9b28-f006097c4feb.png)

However, if we’re going to be providing basemap selection in multiple places we could def make this code more reusable in the future.
