### ISSUE TITLE
"Editing Help" link goes to broken wiki page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1172]
In the Layer Editer a button for "Editing Help" appears. When clicked, it takes the user to a non-existent wiki page. We should either remove this button altogether or send people instead to mapstory.org/getstarted.

![screen shot 2018-01-14 at 2 51 24 pm](https://user-images.githubusercontent.com/2573761/34920597-b58da400-f93a-11e7-827f-c33e1ac00836.jpg)

**Comment by emilyashley** [comment]
@lhcramer @jonpmarino  is it okay to direct it to a functioning, but empty wiki page? http://wiki.mapstory.org/Versioned_Editing

**Comment by jonpmarino** [comment]
I would prefer either mapstory.org/getstarted or on the Wiki, http://wiki.mapstory.org/Get_Started_Guides.

**Comment by emilyashley** [comment]
OK directing it to http://wiki.mapstory.org/Get_Started_Guides

http://wiki.mapstory.org/Versioned_Editing existed but the maploom template had it hard coded to http://wiki.mapstory.org/wiki/Versioned_Editing and that's why it broke. 

We should probably do a sweep of hardcoded wiki links if the routing has changed (or if it often changes when you change a title on the wiki or something) there's probably more broken ones and they will continue to break.

**Comment by emilyashley** [comment]
Closed with commit https://github.com/MapStory/MapLoom/commit/207025205caeee2d0b004041888188cee7ffdc3b
