### ISSUE TITLE
Experiencing randomized layer styling upon import instead of mapstory-orange dots.

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#1181]
<img width="897" alt="screen shot 2018-01-17 at 3 01 13 pm" src="https://user-images.githubusercontent.com/15912063/35067312-2003d484-fb99-11e7-9deb-d7e71f15eb46.png">
<img width="921" alt="screen shot 2018-01-17 at 3 00 55 pm" src="https://user-images.githubusercontent.com/15912063/35067313-201dd6d6-fb99-11e7-951b-2034ecb30595.png">
<img width="822" alt="screen shot 2018-01-17 at 3 00 37 pm" src="https://user-images.githubusercontent.com/15912063/35067314-20305144-fb99-11e7-96ad-1ed4918c8c71.png">

This is a new, unexpected behavior. its supposed to be mapstory orange dots on all layers (outside of stories) unless an admin has associated an sld. Something must've changed somewhere recently to cause this regression.

@DBlasby also confirmed he's experiencing this locally.

**Comment by emilyashley** [comment]
Q: does the mapstory style exist?
A: yes? In geoserver, the `point` style is the correct orange #f59620
<img width="502" alt="screen shot 2018-01-17 at 3 26 21 pm" src="https://user-images.githubusercontent.com/15912063/35067921-274ff8f6-fb9b-11e7-8df7-3608b1d83dc2.png">

however, additional styles have been generated for the newly imported layers?

**Comment by davisc** [comment]
Providing some context...
>In the old (retro) mapstory.org, users could upload an SLD file alongside their data, and the Layer viewer displayed the data with the style. However, retro had the issue where if one user changed the style for a layer in the process of composing a story, the style was then changed for all users of that layer in their story.

This issue was fixed in the Geonode native uploader back then with the introduction of method `def get_sld_for(layer):` which returns a SLD XML snippet with sudo-random css properties for the provided layer. https://github.com/MapStory/geonode/blob/master/geonode/geoserver/helpers.py#L186

osgeo-importer was updated in October of 2017 to use this function so that each imported layer would have its own sld file applied to it. By delegating to this native Geonode function; 1) import and sld creation is in line with core Geonode and 2) supporting Geonode forks have the flexibility to modify the Geonode boilerplate sld snippets as they wish.

https://github.com/GeoNode/django-osgeo-importer/pull/187

You can modify https://github.com/MapStory/geonode/blob/master/geonode/geoserver/helpers.py#L96 and/or disable use of the GenericSLDHandler if unique slds per layer breaks the Mapstory usecase.
