### ISSUE TITLE
Use generic style for thumbnail creation

### ISSUE THREAD

**Issue by goudine** [MapStory/mapstory#1209]
During layer import a geoserver style is created for the thumbnail. That geoserver style is not always consistent.

![varying_gs_style](https://user-images.githubusercontent.com/17364268/35362071-a734aeae-0118-11e8-8874-8c4a3d78204b.png)

(smiling face was custom upload)

There needs to be consistent styling applied to the data depending on the feature type of upload.

**Comment by cuttlefish** [comment]
Is this local or prod?

**Comment by goudine** [comment]
Happens on local and appears to be imitated on prod as well.

A default generated thumbnail points were rendered as red squares.
<img width="544" alt="style1_gs" src="https://user-images.githubusercontent.com/17364268/35417322-c4f09880-01e1-11e8-849b-f82cb5270784.png">

However other thumbnails (also no basemap) were generated with orange spheres.
<img width="291" alt="style2_gs" src="https://user-images.githubusercontent.com/17364268/35417371-f2a84782-01e1-11e8-883c-bf51f487cee1.png">

**Comment by emilyashley** [comment]
Hey checking in on this after standup/parkinglot -  are we trying to tie this in with #1181 ? Are these  two separate issues or are they duplicates? I'd assume the thumbnails are off because the style is off. I didn't realize this was being pulled from the backlog to 'ready' or had been assigned already or I would have pulled in my notes from Jan 17 into the ticket cc: @lhcramer 

@Coop56 @cuttlefish and I spent a while today talking with other osgeo-importer devs on the breaking changes from october causing 1181.

**Comment by davisc** [comment]
Providing some context...
>In the old (retro) mapstory.org, users could upload an SLD file alongside their data, and the Layer viewer displayed the data with the style. However, retro had the issue where if one user changed the style for a layer in the process of composing a story, the style was then changed for all users of that layer in their story.

This issue was fixed in the Geonode native uploader back then with the introduction of method `def get_sld_for(layer):` which returns a SLD XML snippet with sudo-random css properties for the provided layer. https://github.com/MapStory/geonode/blob/master/geonode/geoserver/helpers.py#L186

osgeo-importer was updated in October of 2017 to use this function so that each imported layer would have its own sld file applied to it. By delegating to this native Geonode function; 1) import and sld creation is in line with core Geonode and 2) supporting Geonode forks have the flexibility to modify the Geonode boilerplate sld snippets as they wish.

You can modify https://github.com/MapStory/geonode/blob/master/geonode/geoserver/helpers.py#L96 and/or disable use of the GenericSLDHandler if unique slds per layer breaks the Mapstory usecase.

**Comment by Coop56** [comment]
This was resolved with the fix to the default styles in Geoserver.  Closing.
