### ISSUE TITLE
Configure geowebcache for MapStory

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1212]
Issue:

Smooth and fast playback of layers and stories is critical for MapStory success. Right now our playback is slower than it could be due to the fact that we have caching turned off. Caching on the retro MapStory site supported faster playback.

The MapStory project supported time from @smithkm to work on dependent issues in GWC with the goal of getting a caching implementation into MapStory. We need to see if those issues are closed or others are needed, i.e #352 . Also what other work besides @smithkm is needed before turning on our caching (i.e. #466 was ticketed before)?

**Comment by cuttlefish** [comment]
Also see #352 and #353

**Comment by DBlasby** [comment]
So, Funny Story, staging actually already has GWC enabled on it.  Production DOES NOT.
(I verified the StoryLayer viewer was using cached tiles - I have NOT verified with Story Viewer/Composer)
So, if you look at the performance difference between Staging and Production, you can see the difference the GWC caching does.  
To make a long story short, for most layer (i.e. not huge ones), there isn't a lot of difference (but its definitely faster).
I think this has to do with SSL connection handshaking (my guess) - most of the time is shown in connection setup (>300ms).
There's also quite a bit of time spent waiting - most browsers only allow for 8 simultaneous downloads from the same server.  So, when you're moving from one timeslice to another (requesting > 8 tiles in one go), you are more than likely waiting for some tile to arrive before requesting the rest.  This adds quite a bit of delay.  You can see this in the Network tab of your browser debugger. Typically, I'm seeing between 150ms to 700ms for tiles to arrive (I'm on a "normal" home internet) with little time spent in actual xfer (typically 2-3kb size).  People on the east coast might see this much faster due to shorter round trips (esp for SSL handshakes) since staging is on US-EAST.  There could be internal AWS roundtrips as it talks to an EFS fileshare.
.
To see if a WMS request is tiled, look at your WMS response headers in the browser debugger - you should see `geowebcache-cache-result: HIT` (the first request might be a MISS, but all subsequent requests to the tile (i.e. after refreshing the page) should be HIT. If not, the client and server do NOT agree on the tile gridset).
You can see where GWC is storing tiles by going here - https://docker/geoserver/gwc - in the Storage Location section near the bottom.
To have this work the way we are using the WMS, GWC needs to have three configurations set (cf. geoserver - Tile Caching - Caching Defaults);
* Enable direct integration with GeoServer WMS
* Enable WMS-C Service 
* Automatically configure a GeoWebCache layer for each new layer or layer group
.
This has been running on Staging for quite a while, so I expect its fairly robust.
.
To get this to production;
a) verify that story viewer and composer are "the same as storylayer viewer" (i.e. using WMS so geoserver is using cached tiles)
b) enable above setting on production
c) figure out and configure Disk Quota (not currently on Staging) - we need to retire old tiles or we will use a lot of expensive diskspace.
d) verify its not causing new problems
e) likely some other trouble shooting and setup (i.e. making sure each WMS layer has a GWC caching layer)
.
Looking at the new composer viewer, it appears to be making cached requests.
