### ISSUE TITLE
The `restart django` task fails on first run.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory#22]
The restart django task attempts to restart django before it has been started.  I can temporarily fix this by changing the state to `started` here: https://github.com/MapStory/mapstory-geonode/blob/master/scripts/provision/handlers.yml#L10.  I'm sure there is an easy way to add some conditional logic here.

```
NOTIFIED: [restart django] **************************************************** 
failed: [192.168.56.151] => {"failed": true}
msg: FAILED: attempted to kill gunicorn-django with sig SIGTERM but it wasn't running
gunicorn-django: ERROR (already started)
```

**Comment by jwood106** [comment]
Saw Tyler created this issue.  Pasting a change I made locally in attempt to address this issue.  Not convinced it is the solution, and may be or may spark better idea.

Synopsis: add a 'start django' task and run both the existing 'restart django' and the new 'start django' tasks, allowing the provision to continue (instead of the current halt) if it fails.  If django is already started, 'restart-django' task should succeed, if django is not already started, 'start django' task should succeed.

Changes to two files:

1. scripts/provision/admin.yml
(add use of start django)
 - name: gunicorn-app
   copy: src=files/gunicorn-app.sh dest=/srv/scripts/gunicorn-app.sh mode=650 owner=mapstory group=www-data
-  notify: [restart django]
+  notify: [start django, restart django]
   tags: [config, files, gunicorn]
 
 - name: supervisor-gunicorn
   copy: src=files/supervisor-gunicorn-django.conf dest=/etc/supervisor/conf.d
-  notify: [reload supervisor, restart django]
+  notify: [reload supervisor, start django, restart django]
   tags: [config, gunicorn]

2. scripts/provisions/handlers.yml
(add definition of start django, add ignore_errors to existing restart django)

- name: restart django
  supervisorctl: name=gunicorn-django state=started
  sudo: yes
  sudo_user: root
  notify: check django running
  # jcw - allow it to fail, might not be started.
  ignore_errors: True

- name: start django
  supervisorctl: name=gunicorn-django state=started
  sudo: yes
  sudo_user: root
  notify: check django running
  # jcw - allow it to fail, might already be started.
  ignore_errors: True

**Comment by garnertb** [comment]
This is fixed.
