### ISSUE TITLE
Expose keyboard shortcuts and mouse functionality to users for mapping contexts

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#287]

**Comment by emilyashley** [comment]
i.e. Interaction Features, Map Controls

Address what is currently available in different contexts (composer, editor, story viewer, layer viewer) and consider limiting / expanding uses and communicating what's available. Be intentional. 

examples:
- zoom box
- zoom wheel
- dragging
- click, double click

Relates to Zoom controls in the interface, as well (+ -, slider, zoom to world)
