### ISSUE TITLE
Fully collapse sidebar into hamburger menu

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#310]
Currently, the viewer sidebar collapses to the LEFT, and partially shows. The ideal behavior is for the sidebar to fully collapse, and to be accessible by clicking the hamburger menu at top left.
![screen shot 2016-12-12 at 9 44 36 am](https://cloud.githubusercontent.com/assets/2573761/21105473/f05b654c-c04f-11e6-8d32-aaa170d12764.jpg)

**Comment by glynnis** [comment]
@jonpmarino Was playing around with this in my browser and doing this would be pretty straight forward (for collapsed state):
<img width="1092" alt="screen shot 2017-04-20 at 4 06 58 pm" src="https://cloud.githubusercontent.com/assets/1529366/25252856/36a16cb4-25e4-11e7-9be0-a8d01b1c9b18.png">

Is this what you had in mind when you said "The ideal behavior is for the sidebar to fully collapse, and to be accessible by clicking the hamburger menu at top left"? If so, one suggestion I would make would be to show some text along with or instead of an icon when the sidebar is collapsed so that the user doesn't miss the "expand" button. Depending on map content (like the default orange for polygons) or base tiles (like the geography classroom) it might be easy to miss over on the left side.

**Comment by jonpmarino** [comment]
@glynnnis, yup that's it. I like your suggestion of text. run with it!

**Comment by jonpmarino** [comment]
looks good on demo (May 1)

**Comment by jonpmarino** [comment]
looks good on prod! closing.

![screen shot 2017-05-10 at 5 43 43 pm](https://cloud.githubusercontent.com/assets/2573761/25924418/437a143a-35a8-11e7-8639-18879d916906.jpg)
