### ISSUE TITLE
Link to username in Contributions tab goes to an error page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#447]
(Confirmed with @reynalddizon on Feb 8. Using Safari 10.0.2 and Chrome Version 55.0.2883.95).

Issue:

In the Contributions tab for a layer, there is a link to user profiles underneath each edit. The link path generated when clicking the username goes to a broken link.

![link](https://cloud.githubusercontent.com/assets/2573761/22747158/d86fd94e-edeb-11e6-8a6a-f4e7fd0d436b.jpg)

![screen shot 2017-02-08 at 10 39 25 am](https://cloud.githubusercontent.com/assets/2573761/22747095/aa370c64-edeb-11e6-824f-3a8a60ade7ae.jpg)

Steps to reproduce:

1. From search, click on any StoryLayer. Make sure it is a StoryLayer that has an entry underneath the "contributions" tab.
2. Click on a username link underneath the contributions tab.
3. The link path seems to be trying to use the full First and Last name rather than the username, which may be the right thing to do. But, that link path doesn't correspond to the way we currently handle profile page URLs, which use username. We either need to change the how the profile URL is handled, or fix the link path here.

**Comment by emilyashley** [comment]
Odd, I had already caught this at whatever state our site was in on Nov 30 --- wonder if geogig changed at all with committer/author bits. If they did, we'll need to replace it thruout the html. 

we're using usernames as unique identifiers for edit history, not first name last name as we had originally asked for because display names can be edited after the fact and usernames can't

Try changing `commit.committer.name` to `commit.author.name` [here](https://github.com/MapStory/mapstory/blob/master/mapstory/templates/layers/_geogig_layer_detail.html#L29) or anywhere else we're using committer

also,  let's be thorough and check to see if it's the same for legacy data and new data.

**Comment by glynnis** [comment]
Notes from 2/8 call:
@davisc @emilyashley May be a deeper issue with how GeoGig is managing this. @davisc will research this.
