### ISSUE TITLE
Enable user to set zoom level setting for layer

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#509]
Allow user to modify the position and zoom level of a layer.
Currently the importer handles this. However it can't be modified, and if a layer is manually created it can't be set. Maybe relation to @smithkm #353.

This issue would require mockups for a set in the Create Layer workflow where a user could set their bounding box.

**Comment by jonpmarino** [comment]
just flagging for @glynnis @emilyashley for future consideration. This is an issue, to me, conceptually connected with the question of adding some style editing for layers only. Setting a "zoom" is currently only available in stories, not layers. So adding ability to set custom zoom levels to layers will be a new addition as part of open-data-community enhancements. Makes sense, especially for CREATED layers, since the zoom level that makes sense for them will change as features are added through editing.
