### ISSUE TITLE
Org Page MVP

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#651]
Part of the MapStory community and business model is to provide an "organization page" identity in addition to and separate from the regular account. Regular accounts should follow a real-names human identity policy, so organization pages offer an opportunity for organizations to gather the range of work they do and present it under the banner of an organization. For example, if the Chicago Council on Global Affairs (https://www.thechicagocouncil.org/) wants to contribute layers and stories about international affairs under their corporate name, rather than on an individual's profile, they will set up an Org page, perhaps www.mapstory.org/ChicagoCouncil.

This issue outlines the MVP items that will allow us to start getting Organization pages going. Separate sub-issues will be necessary.  Future iterations can build on the MVP as user research comes in.

**MVP**

On the profile page itself we can make some modest tweaks to the individual profile and re-purpose for orgs:

- Change "First and Last Name" fields to Organization Name
- Remove "Education" field
- Add field for "Organization Website" link
- Hide VTC option

Otherwise, the Org page profile can operate the same as the individual profile for now. Once an Org profile is active, a user will log-in to the org page using the Org username and password. That user can then author journal articles, upload icons, edit the profile, favorite content, and create content under the identity of the organization.

**Other Items**

- add a filter to Storytellers search in Explore so that a viewer can filter by Organizations only

- Have URL model for organization pages so they can follow a simple convention, such as mapstory.org/Name or if necessary, mapstory.org/organization/Name (or, could we just use the same mapstory.org/storyteller convention for org pages too?). This will help organizations easily share their profile URL with colleages, etc...similar to other social media profiles.

- Create a new simple page with information for users on setting up an org page. This page will have pricing information, sales-pitch content for why an org page is worth setting up, and directions for how to initiate set-up. It can be linked to from a variety of places (such as the sign-up modal, Get Started section on Organization Pages, Donation page, etc.)

- Create a form that is linked to, or part of the information page for organizations that allows user to 'request' an organization page. The form should ask for: 

1. the requested org page slug/user name
2. password
3. a point of contact and email
4. monthly digest?
5. terms and conditions reviewed?
6. other confirmation questions (i.e. if requesting nonprofit rate, proof of nonprofit status)...look to https://www.google.com/nonprofits/account/signup/us?hl=enfor example
7. Pay categories options. I suggest 3 to start: 1) nonprofit 2) corporate 3) sponsor. We can process payment by using our existing Paypal donation mechanism, https://www.paypal.com/donate/?token=PLn4eKnG7_EdGZUBgx6SZuymg9KCy8OaGXhttQpU34BNXNzEWpOsjHN56PSiSZM1Erz-4W). Nonprofit orgs would be expected to make a minimum required donation of a certain amount. Corporate orgs would be expected to make a minimum required donation of a larger amount. For the third option, "Become a MapStory Foundation sponsor", we'd ask the org to contact us to discuss sponsorship details.

Question: what is the workflow for the final Org profile creation step? Is it automatic, or is a manual admin review necessary? Either way, presumably the POC email account would get a confirmation email with the basic message of "congrats, your organization page is now active" with directions on how get started completing the profile and using it. 

**Stretch goals for future**

We should offer an "analytics digest" at an increased rate to Org Page owners that request it. The analytics would provide intel on use of layers by users across the site, edit history, stories published, data downloads, and other items of interest to Org Page owners.

**Note**

Previous Org page issues to check: noting old tickets for previous org page implementations here for background
https://github.com/MapStory/mapstory-meta/issues/1102
https://github.com/MapStory/mapstory-meta/issues/1400

A previous mockup done by Steven Schyu in 2013, 
https://sites.google.com/a/opengeo.org/mapstory-ui/organization-pages.

Notes from previous feedback sessions, https://docs.google.com/a/mapstory.org/document/d/1uDRTk0ziqez43k_VZBwylWCyKwBp5eKtpWDc4Oy_zR8/edit?usp=sharing

**Comment by glynnis** [comment]
@jonpmarino: @Coop56 pulled me in to consult on design/UI stuff for this, and we met this morning to discuss. We've reviewed the content of this issue as well as the Organization section of the roadmap (https://github.com/MapStory/mapstory/wiki/Explore-%26-Content-Discovery-Improvements#organization-profiles) to compile questions and take notes on possible requirements. 

@Coop56 will be sending out an invite so we can meet to review these notes and go over requirements/implementation questions as well as your vision and discuss possible iterative releases for this feature set.

Here are our notes (which we can review together when we meet):

## High level vision
* What is the sales pitch for org pages? Why should a user want an org page? Knowing the answer will help define what the org page design looks like, what content gets prioritized, etc.
* Who is the target audience for pitching this to? Could we do some user research with someone who would be a good candidate to validate our assumptions about design?
> The Org profile design should feel like a "home page for an organization". We should consider a nice carousel for layers and stories the Org wants to feature.
* What's the vision for what a "home page for an organization" looks like? What is customizable about an org page?
* What is MVP? What iterations could be released as feature-complete as more work gets done?

## Path to creation
> If someone is interested in launching an org page in mapstory.org, they should complete a request. A mapstory admin will then create it via django-admin (and discuss payment/cost).
* If we go with this flow for creation, my guess is the point of entry wold be a contact form
  * What fields are needed so that we have all info we need for setting up in django?
  * Are fields only so that we can contact the person interested?
  * What other explanatory text or value proposition should be on the "want an org page on MapStory?" request page? 
* Could we automate this/not have a manual process for creating org pages? Having to contact to find out pricing/get something manually created is a big barrier for users. Ideally we'd have a pricing page, allow users to create pages on their own, and require payment if they want to publish the org page (and keep it private until then).
  * Perhaps this is where iterative steps come in, and we can define some milestones?

## Content and customization
> Once a user is made a manager of an org page, while logged in as themselves on mapstory.org, the user should be able to go to the Org Page and customize it
* In what way should users be able to customize an org page?
> Consideration: On a FB org page, there is an option to "post as an organization" or "post as an individual". For example, an admin of the MapStory facebook page can choose to like, comment on, or favorite things on Facebook as mapstory rather than their name. Do we want this?
* Should a user's profile page change if they manage (or are members/fans of) one or multiple organization pages?
* What content should appear on an org page? What fields would exist for someone creating/editing an org page? (ex: established date, description, mission, location, what social media links)?
> The org page should also be able to share journal entries, icons, an activity feed, and basic about information (location, about text, social media links) just like a normal user profile
* Where do journal entries show for Org pages? 
* How does a user distinguish between their own journal entries and an org page's journal entries?
* What things do I see when I visit an org page? Can we get a list of content that should appear? What content is the priority or main focus?
* What should appear in the activity feed? How should icons appear?
* Should org pages be able to associate stories or layers with their org? Do they need to request permission from the user who added that content and have it approved if that user isn't part of the group or doesn't approve it? Where/how do they display?
* Do org page owners decide what gets featured, or is it all content/automatically generated?
* If a layer belongs to an organization, do we display their name/info on a layer page (even if they didn't initially create/upload the layer)? Do we also display the user who uploaded it, or does the username of the original importer get overwritten by the org?
  * Where else do organization names/info need to be displayed around the site?

## Permissions and account management
> provide an "organization page" identity in addition to and separate from the regular account. 
> Once a user is made a manager of an org page, while logged in as themselves on mapstory.org, the user should be able to go to the Org Page and customize it
* Our assumption from the above text is that org pages will be managed by regular user accounts rather than via a separate account/login specifically for an org page. Is this correct?
* Can multiple users be managers of the same org page? 
* Is there a limit for # of org page managers? 
* Can a user manage more than on org page? 
* Can management privileges for an org page be transferred? What process should exist for that (is it all manual through django admin)?
* Are there different levels of permissions or roles for org pages? For example, in Google Docs there are "owners" vs. "can edit" vs. "read only" share access. In Facebook pages, there are six different roles: admin, editor, moderator, advertiser, analyst, and live contributor. My guess is we don't want or need something this complex, and that maybe just "admin" and "editor" would be sufficient. What's in scope for now?
* Should a manager for an org page be able to manage these permissions through a UI, or is it something we will do manually through django admin? ("A registered user should then be able to be made a 'manager' of an organization page by a mapstory admin in django-admin")
* Are there "members" for an org page that can't publish or manipulate the page itself (like "fans" on Facebook), and is that a role we need to account for?
* Do members who join have to be approved? Can anyone join? Do they have to request access, or does the org page have to invite them?
* Are there private org pages? (ex: Facebook groups have private groups that are not visible via search and are invite only, public groups that you can join instantly, public groups that require approval to join). 
> Consideration: On a FB org page, there is an option to "post as organization" or "post as an individual". For example, an admin of the MapStory facebook page can choose to like, comment on, or favorite things on Facebook as mapstory rather than their name. Do we want this?
* Should a user be able to change which account/org they are acting as in the navigation menu, or do they have separate nav items that allow them to switch between different publishing mechanisms (i.e. a dropdown on a journal entry for "post as org" vs. "post as [username]")?

## Other considerations
* Where in Explore do org page results show? Do they display separately from storytellers/content in their own tab? What filters should exist for Explore and org pages?
  * URL routing (mapstory.org/starbucks)
  * unique namespacing
  * certain characters not allowed
  * limit in length?
  * certain names are reserved ("layers", "story", "account", "accounts", "map", "maps" etc. -- anything else that we need to reserve for current routing)
  * modify existing "organization" routes
