### ISSUE TITLE
Revise Organization Page wireframes based on user feedback

### ISSUE THREAD

**Issue by glynnis** [MapStory/mapstory#693]
Once #692 is complete, revise the wireframes for Org Pages based on user feedback.

Finalize content positioning, copy, and ensure technical feasibility before moving on to high fidelity mock-ups.

**Comment by glynnis** [comment]
Organization page research findings are in this presentation:
[Research Findings - Organization pages.pdf](https://github.com/MapStory/mapstory/files/1025777/Research.Findings.-.Organization.pages.pdf)

Initial wireframe work that was used to conduct research is on InVision here: https://invis.io/VKBO9KJ5W

Design assets for that work are here: https://github.com/MapStory/mapstory-assets/tree/master/design_assets/2017_04_21%20-%20org%20pages/wireframes

**Comment by josellausas** [comment]
Changes need to be made to wireframes to reflect UX findings:

- [x] "About this organization" needs to allow for multiple Organization URL's.
- [x] Add Instagram to social media section.
- [x] Remove icons section.
- [x] Add multiple author labels.
- [x] Featured MapStories & StoryLayers should be the first section.
- [x] Showing 'last updated' instead of 'created date' in all contexts is more useful.

**Comment by josellausas** [comment]
Updated assests repo: https://github.com/MapStory/mapstory-assets/pull/9

**Comment by josellausas** [comment]
Feedback has been integrated into new design.
