### ISSUE TITLE
Create mockups for gazetteer MVP integration into Explore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#732]
**User Story**

As a user, when I explore in MapStory, I want to be able to see all the layers or stories that have features concerning a specific place that interests me...a capability made possible by integration of the gazetteer layer into the mapstory explore page.

**Acceptance Criteria**

- Indicate how place specific information generated by gazetteer could be integrated into the current MapStory explore page

**Deliverables**

- [ ] Conceptual mockup that can be used for discussion and translated into a clickable mockup for implementation for assigned developers

This work is related to the Roadmap here, https://github.com/MapStory/mapstory/wiki/Data-Model-Improvements#gazetteer

**Comment by jonpmarino** [comment]
@reynalddizon latest mockup for gazetteer information integrated into explore/discover. For discussion on UX architecture.
[gazetteer-explore.pdf](https://github.com/MapStory/mapstory/files/1092648/gazetteer-explore.pdf)

**Comment by rob-metalinkage** [comment]
There are some endpoints to get this info (i can improve when we get to lab.mapstory running)
https://gazetteer.mapstory.org/rdf_io/to_rdf/location/id/4?_format=ttl
(or https://gazetteer.mapstory.org/rdf_io/to_rdf/location/id/4?_format=json)

gives you the list of layers a name was found in.

embedded in this is a convenience API that the django model can build, because it knows which fields it looked in:
https://gazetteer.mapstory.org/gazetteer/location/4/sourcewfs/istanbulevents

and for convenience debugging:
https://gazetteer.mapstory.org/gazetteer/location/4/sourcewfs/istanbulevents?_format=html

This i think gives you feature level explorer options.

We can also discover layer level links - but these need to be weighted somehow by the link coverage - how "related" is a layer. I can generate stats and expose them via an API - but Iwould like to know what is going to be most useful.

**Comment by rob-metalinkage** [comment]
will copy these comments to #784
