### ISSUE TITLE
run test datasets through mapstory os-geo importer master

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#734]
**Acceptance criteria:**

Use test data provided by Nitin Gadia, Karl Phillips and Rey Dizon to check performance of os-geo importer master build in mapstory and ticket any issues that arise.

**Comment by Coop56** [comment]
This testing is now done, and with it I fixed two issues.  I fixed an issue where any file that had a filetype with multiple dots in it would fail because django-osgeo-importer would tried to process it and not ignore it like we wanted.  I also fixed a local mapstory settings issue to find the correct path for our EPSG codes.  This issue also surfaced a projections issue that we're having, we're not supporting many projections because django-osgeo-importer is failing to find and assign the correct projection.  A new issue will be created about projection support.
