### ISSUE TITLE
Change homepage to use data from django admin

### ISSUE THREAD

**Issue by josellausas** [MapStory/mapstory#778]
Change hard-coded data to use django-admin. Ref #833

**Comment by jonpmarino** [comment]
Low hanging fruit:

- footer text (bottom left text in new homepage)
- favicon
- logo
- subtitle ('hero'/call to action)
- sponsor logos (upload via png)
- feature mapstories (via 'is featured' checkbox in the mapstory django list)

**Comment by emilyashley** [comment]
(duplicate list from Marino above)

### done:
- [x] footer text (bottom left text in new homepage) --  #777 
- [x] feature mapstories (via 'is featured' checkbox in the mapstory django list) -- #938 / #833 

### ready to be tested w/ deployment:
- [x] sponsor logos (upload via png) -- https://github.com/MapStory/mapstory/commit/bec327d34bd7c8ab6bafa518c8950b3ca187dc85

- [x] subtitle ('hero'/call to action) -- https://github.com/MapStory/mapstory/commit/7cf78b9c332283949850c51557a203babc3459ad
- [x] favicon
- [x] logo

Addressed sponsor logos on this ticket on `admin-sponsors` branch with https://github.com/MapStory/mapstory/commit/bec327d34bd7c8ab6bafa518c8950b3ca187dc85

**Before** making a pull request, we'll need to verify that the sponsor info from the django admin section persists on redeployment (both prod and local?), otherwise the section will be empty and the images and links will have to be added every time.
