### ISSUE TITLE
Create first draft UX in lab.mapstory.org for gazeteer functionality

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#784]
See #731 #732 for initial thinking

**Comment by rob-metalinkage** [comment]
There are some endpoints to get this info (i can improve when we get to lab.mapstory running)
https://gazetteer.mapstory.org/rdf_io/to_rdf/location/id/4?_format=ttl
(or https://gazetteer.mapstory.org/rdf_io/to_rdf/location/id/4?_format=json)

gives you the list of layers a name was found in.

embedded in this is a convenience API that the django model can build, because it knows which fields it looked in:
https://gazetteer.mapstory.org/gazetteer/location/4/sourcewfs/istanbulevents

and for convenience debugging:
https://gazetteer.mapstory.org/gazetteer/location/4/sourcewfs/istanbulevents?_format=html

This i think gives you feature level explorer options.

We can also discover layer level links - but these need to be weighted somehow by the link coverage - how "related" is a layer. I can generate stats and expose them via an API - but Iwould like to know what is going to be most useful.
