### ISSUE TITLE
User can't change password

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#957]
https://beta.mapstory.org/account/password/ is broken

![image](https://user-images.githubusercontent.com/1152120/29373577-b59a71d8-827c-11e7-8f8d-6d981cba521f.png)

**Comment by emilyashley** [comment]
hmmm weird, `/account/password/reset/` works. Lemme look at the templates.

I wonder if there’s a bigger issue with us grabbing/inheriting templates from core geonode apps (account, avatar, etc)

I pulled in the templates to mapstory for avatar to fix this with PR #904 , but if there’s a issue a step up we might want to address that.

**Comment by Coop56** [comment]
This issue revolves mostly around an outdated package, and is resolved in Geonode 2.7.x.  I'm evaluating our upgrade options.

**Comment by Coop56** [comment]
It took some investigating to figure out why this wasn't getting the right template.  The template loaders happened to be hitting the pinax library before geonode, so it was pulling a template of the same name from that app rather than the geonode template for changing your password.  I've submitted PR https://github.com/MapStory/mapstory/pull/967 that will fix this issue as well as any other template issues that may have been caused.  The template order that django will load templates in now is our own mapstory templates, then geonode, then any other third party app templates last.

**Comment by emilyashley** [comment]
Closed with #967
