### ISSUE TITLE
Map symbology does not change when an icon is used for a point style

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#984]
Expected behavior:

As a user, I expect that when I use an icon uploaded from the icons commons for a point style when I am composing a mapstory, that that icon will appear on the map as a style for my point features.

Current behavior (based on beta.mapstory.org on August 31 at 5:00pm CST using Chrome Version 60.0.3112.113)

When I am in composer, I am able to find an icon and add it to my style. The icon appears in the small preview window in the sidebar. But, the icon does not appear on the map interface.

For example, here I cam composing a story using a "prisoner" icon, I can see it in the style, but it doesn't appear on the map. My features are still orange dots.

![screen shot 2017-08-31 at 5 12 14 pm](https://user-images.githubusercontent.com/2573761/29947601-150c257c-8e70-11e7-8dda-0326d7d1cfcc.jpg)

**Comment by davisc** [comment]
**Update**  The current version of beta.mapstory.org appears to build the sld with the referenced icon image, however, Geoserver is failing to successfully apply the style which results in blank tiles. @jonpmarino can you confirm this updated behavior of returned blank tiles so that we can update this issue accordingly?

**Test Case: Icon applied to the prisons layer**
https://beta.mapstory.org/icons/icon/259?fill=%23f59620&amp;stroke=%23000000

**SLD Generated by Composer:**
```xml
<sld:StyledLayerDescriptor xmlns:sld="http://www.opengis.net/sld" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
<sld:NamedLayer>
<sld:Name>prisons_498953e1</sld:Name>
<sld:UserStyle>
<sld:Name>yahoo-0-0-simple-point-PRISONS</sld:Name>
<sld:FeatureTypeStyle>
<sld:Rule>
<sld:PointSymbolizer>
<sld:Graphic>
<sld:ExternalGraphic>
<sld:OnlineResource xlink:href="https://beta.mapstory.org/icons/icon/259?fill=%23f59620&amp;stroke=%23000000"/><sld:Format>image/svg+xml</sld:Format></sld:ExternalGraphic>
<sld:Opacity>0.7</sld:Opacity><sld:Size>10</sld:Size>
</sld:Graphic>
</sld:PointSymbolizer>
</sld:Rule>
</sld:FeatureTypeStyle>
</sld:UserStyle>
</sld:NamedLayer></sld:StyledLayerDescriptor>
```

**Geoserver Error:**
`
Rendering process failed java.lang.NoClassDefFoundError: Could not initialize class org.apache.batik.bridge.CursorManager Could not initialize class org.apache.batik.bridge.CursorManager
`

**Comment by jonpmarino** [comment]
Tested adding an icon to a style in composer on the evening of October 4. As a user, my experience was similar to the description above in the original ticket. I see the icon in the styling sidebar to the left, but do not see the icon applied to the point style on the map interface. I also don't see the icon in the Legend as expected. In the published story (https://beta.mapstory.org/story/icon-test-october-4-309/) I see no features. @davisc thanks for the description above. Feel free to adjust the issue ticket (or break into multiple tickets) however you need as you work the problem. Happy to provide a demo of what I'm seeing. If others see different outcomes when using icons in styling, please share.

![screen shot 2017-10-04 at 9 48 53 pm](https://user-images.githubusercontent.com/2573761/31209175-d447be1c-a94e-11e7-9785-0ce946bdb68e.jpg)

![screen shot 2017-10-04 at 9 54 16 pm](https://user-images.githubusercontent.com/2573761/31209177-d88d6b5c-a94e-11e7-8921-d0e783edeb2c.jpg)

**Comment by davisc** [comment]
@jonpmarino After further investigation, there are two issues here.

@cuttlefish I've tested on Geoserver 2.9 and the sld works, however, on Geoserver 2.11.2 the following exception is returned. Also it appears that in Geoserver 2.11.2 there is no way to preview the sld in the style admin interface.

```
Rendering process failed java.lang.NoClassDefFoundError: Could not initialize class org.apache.batik.bridge.CursorManager Could not initialize class org.apache.batik.bridge.CursorManager
```

As a non admin user, the updated sld fails to be persisted due to a Geonode internal server error in route /gs/rest/style

**Comment by jonpmarino** [comment]
this is still relevant for new composer
